#include "q.h" // to declare function go()

// see loop-expected-output.txt for the correct output generated by ALL the input tests given in loop-input.txt
int main(void)
{
    go(); 	//calling function go()
    return 0;
}